### ISSUE TITLE
How to run the `languagetable.py`

### ISSUE THREAD

**Issue by Lr-2002** [bytedance/IRASim#2]
Hi, thanx for your impressing work. 
I'm trying to use the `languagetable.py` to make sure how to work with IRASim
While Now the 'args.base_dir'  is missing and It seems that the `vae` model is not involved in the `pretrained_models`, Could you give more advice in re-run the `languagetable.py` ?

**Comment by neurlps-2024-10019** [comment]
Hi, thank you for your attention.

You can set args.base_dir = '' on line 62 of util.py. I have also updated the code to include this line. args.base_dir is a common prefix for data storage, intended for switching between different cloud drives.

You can download the VAE model (stabilityai/stable-diffusion-xl-base-1.0) from [Hugging Face](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0).

**Comment by fangqi-Zhu** [comment]
Hi, thank you for your attention.

You can set args.base_dir = '' on line 62 of util.py. I have also updated the code to include this line. args.base_dir is a common prefix for data storage, intended for switching between different cloud drives.

You can download the VAE model (stabilityai/stable-diffusion-xl-base-1.0) from [Hugging Face](https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0).

**Comment by Lr-2002** [comment]
okk, Thanks a lot. Is it necessary to dowload all the `train`, `eval`, `ckpt` to run the languagetable.py? I've just download `eval` and `ckpt`, It seems not easy to run the code.

**Comment by fangqi-Zhu** [comment]
To run `application/languagetable.py`, you just need to download the checkpoint. I have checked the code before publishing; just some paths need to be set. Feel free to ask if you encounter any issues with the code.

**Comment by Lr-2002** [comment]
ok, could I have your wechat to talk about the detail in re-produce? Maybe i could give more detail about re-product for this great work after run it from scratch!

**Comment by Lr-2002** [comment]
What's more the languagetable.py seems to relay on latent video and video path a lot, It might be some mistake in pushing?

**Comment by Lr-2002** [comment]
ok.. I've fixed all the problem. But to be honest now the code seems have some problem for only checkpoints.tar.gz download

**Comment by Lr-2002** [comment]
to be honest... you push the previous-commit absolutly... the language table has too much not-related code

**Comment by fangqi-Zhu** [comment]
Sorry, I forgot that language_table.py depends on the eval dataset. Using the eval dataset, you can try more examples, or you need to modify the code to encode the given image provided on GitHub. And I believe there is no unrelated code in language_table.py since code is cleaned before publishing. Only paths you need to setup to run the code. Feel free to reach out if you encounter other bugs.

**Comment by Lr-2002** [comment]
Okay, Thx a lot. There is no more problem and I'l close the Issue.
Thanks for your work and patient help
