### ISSUE TITLE
downloading the languagetable train data is slow and unreliable

### ISSUE THREAD

**Issue by WilliXL** [bytedance/IRASim#3]
i'm trying to download the data using the `scripts/download.sh` script but when downloading the `languagetable_train_data` file it downloads at very slow speeds (~200kb/s) and sometimes will fail during the download with this message:
```
curl: (18) transfer closed with 203424348646 bytes remaining to read
```
is there a more reliable way to download this data?

**Comment by fangqi-Zhu** [comment]
Hi, sorry for late reply. 1. you can try to resume the download process. 2. I will try to transfer this dataset to Google Cloud. But it takes some time. I will fix this problem recently. Sorry for this problem.

**Comment by WilliXL** [comment]
Hi yeah I was able to use `curl -C -` to continuously resume the download and was able to get the file downloaded!

And no worries about the late reply.

Also was curious if the WeChat group is still available to join. The QR code is inactive now

**Comment by fangqi-Zhu** [comment]
hi, you can scan the right qr code to help you join the wechat group

**Comment by OrangeSodahub** [comment]
@fangqi-Zhu Hi, the qr code is expired.
